2023-08-25 23:54:19,171 - INFO - The returned answer is: {MSG}
2023-08-25 23:55:33,482 - INFO - The returned answer is:
2023-08-26 00:30:36,390 - INFO - error_code=rate_limit_exceeded error_message='Rate limit reached for default-text-embedding-ada-002 in organization org-76mvp15kVvvVP7AfTkEXdsVd on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.' error_param=None error_type=requests message='OpenAI API error received' stream_error=False
2023-08-26 00:30:36,393 - WARNING - Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-76mvp15kVvvVP7AfTkEXdsVd on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method..
2023-08-26 08:34:02,368 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213AF9383D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:34:02,374 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213B142ED50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:34:02,375 - WARNING - Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213AC36F490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')).
2023-08-26 08:34:06,385 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213AEB94D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:34:06,387 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213B13D0F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:34:06,388 - WARNING - Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213AC3D1C10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')).
2023-08-26 08:34:10,394 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213AED0D950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:34:10,395 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213AEBAA210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:34:10,397 - WARNING - Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213B0E24150>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')).
2023-08-26 08:34:14,401 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213B0C329D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:34:14,402 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213B0C31110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:34:14,403 - WARNING - Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213B0C32B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')).
2023-08-26 08:34:22,409 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213AF92E050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:34:22,410 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213AF92D250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:34:22,411 - WARNING - Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213ACA50210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')).
2023-08-26 08:34:32,416 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213B0C32650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:34:32,418 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213ADDF2490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:41:49,780 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213AF9D96D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:41:49,781 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213AEB96510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v1/engines/text-embedding-ada-002/embeddings
2023-08-26 08:41:49,782 - WARNING - Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213AEC641D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')).
